### ISSUE TITLE
Remove the s from minutes if there's just a singular minute

### ISSUE THREAD

**Issue by TheCakegamer** [DamienFlury/go-home#13]
If there's just 1 minute left or 1 hour, remove the "s" so it's "1 hour 1 minute" instead of "1 hours 1 minutes"

e.g.
![you know I had to do it to em](https://user-images.githubusercontent.com/40315936/70920359-c2f47900-2022-11ea-9cb7-c5ebdb9717e9.png)

**Comment by DamienFlury** [comment]
Fixed in v2.2.0.
